default_stages:
    - pre-commit
    - manual

repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.2
      hooks:
          - id: ruff-format
            stages: [pre-commit]
          - id: ruff
            args: [--fix]
            stages: [pre-commit]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/openstack/bashate
      rev: 2.1.1
      hooks:
          - id: bashate
            name: bashate
            description: This hook runs bashate for linting shell scripts
            entry: bashate
            language: python
            types: [shell]

    - repo: local
      hooks:
          - id: ty-check for ps
            name: ty-check for ps
            entry: ty check ps
            language: python
            pass_filenames: false
            args: ["--python=.venv/", "--ignore=unresolved-import"]
            additional_dependencies: [ty]
